name: Five9 Call Log Extraction
run-name: ${{ github.actor }} is running Five9 extraction 📊
on:
  schedule:
    - cron: '0 34 9 ? * * *'
  workflow_dispatch: 
  push:  

jobs:
  Extract-Call-Logs:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " The workflow is now ready to extract Five9 call logs."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run extraction script
        shell: bash
        run: |
          # Build command with only the args that have values
          CMD="python five9_extractor.py \"${{ secrets.FIVE9_CREDENTIALS }}\""
          
          # Only add arguments if they have values
          if [ -n "${{ secrets.SFTP_HOST }}" ]; then
            CMD="$CMD --sftp-host \"${{ secrets.SFTP_HOST }}\""
          fi
          
          if [ -n "${{ vars.SFTP_PORT }}" ]; then
            CMD="$CMD --sftp-port ${{ vars.SFTP_PORT }}"
          fi
          
          if [ -n "${{ secrets.SFTP_USERNAME }}" ]; then
            CMD="$CMD --sftp-username \"${{ secrets.SFTP_USERNAME }}\""
          fi
          
          if [ -n "${{ secrets.SFTP_PASSWORD }}" ]; then
            CMD="$CMD --sftp-password \"${{ secrets.SFTP_PASSWORD }}\""
          fi
          
          if [ -n "${{ vars.SFTP_PATH }}" ]; then
            CMD="$CMD --sftp-path \"${{ vars.SFTP_PATH }}\""
          fi
          
          # Print command (with credentials masked)
          echo "Running command: python five9_extractor.py [CREDENTIALS] [ARGS]"
          
          # Execute the command
          eval $CMD
      
      - run: echo " This job's status is ${{ job.status }}."